with v_stg_hl_agent_master (
SELECT 
    agent_code,
    agent_name,
    gender,
    application_docket_no,
    reason,
    code_gen_date,
    end_date,
    record_insert_timestamp,
    record_update_timestamp,
    employee_code,
    channel_code,
    sub_channel_code,
    dm_code,
    dm_name,
    dob,
    ulip_training,
    record_effective_from_date,
    record_effective_to_date,
    status_code,
    status_name,
    substatus_code,
    substatus_name,
    inactive_date,
    reason,
    source_of_recruitment,
    pan,
    business_status,
    main_channel_code,
    joining_date,
    end_date as end_date_duplicate_entry,
    agent_status,
    designation_code,
    induction_start_date,
    induction_end_date,
    CAST(MD5(NULLIF(CONCAT_WS('||',
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agent_name` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`gender` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`application_docket_no` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`reason` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`code_gen_date` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`end_date` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`record_insert_timestamp` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`record_update_timestamp` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`employee_code` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`channel_code` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`sub_channel_code` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`dm_code` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`dm_name` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`dob` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`ulip_training` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`record_effective_from_date` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`record_effective_to_date` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`status_code` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`status_name` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`substatus_code` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`substatus_name` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`inactive_date` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`reason` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`source_of_recruitment` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`pan` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`business_status` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`main_channel_code` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`joining_date` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`end_date` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agent_status` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`designation_code` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`induction_start_date` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`induction_end_date` AS STRING))), ''), '^^')
        ), '^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^')) AS VARCHAR(16)) AS `rcrd_hsh_id`
        from dataverse_preprod_mirror_hl.stg_hl_agent_master
        ),

v_s_agnt_dtl as (
    SELECT 
    agnt_nm,
    agnt_gndr_cd,
    agnt_applctn_nmbr,
    rjctn_rsn_dscrptn,
    src_cd_gnrtn_dt,
    src_cd_end_dt,
    src_systm_crtd_dt,
    src_systm_updtd_dt,
    emply_cd,
    chnnl_cd,
    sb_chnnl_cd,
    agnt_sprvsr_cd,
    agnt_sprvsr_nm,
    agnt_brth_dt,
    ulip_trngn_flg,
    strt_dt,
    end_dt,
    agnt_stts_cd,
    stts_nm,
    sb_stts_cd,
    sb_stts_nm,
    agnt_inctv_dt,
    agnt_inctv_rsn,
    agnt_rcrmnt_src,
    prmnnt_accnt_nmbr,
    bsns_stts_cd,
    mn_chnnl_cd,
    agnt_jnng_dt,
    agnt_trmntn_dt,
    agnt_stts_nm,
    agnt_dsgntn_cd,
    systm_crtd_dt,
    systm_updtd_dt,
    CAST(MD5(NULLIF(CONCAT_WS('||',
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_nm` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_gndr_cd` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_applctn_nmbr` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`rjctn_rsn_dscrptn` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`src_cd_gnrtn_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`src_cd_end_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`src_systm_crtd_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`src_systm_updtd_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`emply_cd` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`chnnl_cd` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`sb_chnnl_cd` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_sprvsr_cd` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_sprvsr_nm` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_brth_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`ulip_trngn_flg` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`strt_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`end_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_stts_cd` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`stts_nm` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`sb_stts_cd` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`sb_stts_nm` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_inctv_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_inctv_rsn` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_rcrmnt_src` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`prmnnt_accnt_nmbr` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`bsns_stts_cd` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`mn_chnnl_cd` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_jnng_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_trmntn_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_stts_nm` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`agnt_dsgntn_cd` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`systm_crtd_dt` AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(`systm_updtd_dt` AS STRING))), ''), '^^')
    ), '^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^||^^')) AS VARCHAR(16)) AS `rcrd_hsh_id`
    from dataverse_preprod_ontology.s_agnt_dtl
)

